# Generated by Django 6.1.1 on 2026-09-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='professional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
