# Generated by Django 6.1.1 on 2026-09-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="professional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="professionals.professional",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["professional", "scheduled_at"],
                name="appointment_prof_date_idx",
            ),
        ),
    ]
