# Generated by Django 6.1.1 on 2026-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('professionals', '0003_rename_adress_professional_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('professional', 'scheduled_at'), name='unique_professional_appointment_time'),
        ),
    ]
